# What is Tensorflow?

is an open-source tool `created by Google to help build and run machine learning models`. Think of it like a `toolbox for teaching computers to learn from data`. It’s used for tasks like recognizing images, understanding speech, or predicting trends by processing lots of numbers and patterns.

**Other Resources**
- [Tensorflow Fundamentals](https://github.com/mrdbourke/tensorflow-deep-learning/blob/main/00_tensorflow_fundamentals.ipynb)
- [Rules of Machine Learning](https://developers.google.com/machine-learning/guides/rules-of-ml)

# What is a Tensor?

is a fundamental concept that represents data in a flexible, mathematical way.

A tensor is like a `container for numbers, organized in a specific shape`. Think of it as a way to store and manipulate data, whether it’s a single number, a list, a table, or even more complex structures. Tensors are the `building blocks that TensorFlow (an open-source AI library) uses to perform calculations, especially for tasks like training neural networks`.

You can picture tensors as:

- A single number (like 5).
- A list of numbers (like [1, 2, 3]).
- A table or grid of numbers (like a spreadsheet).
- Or even a 3D or higher-dimensional structure (like a stack of spreadsheets).

**Key Properties of a Tensor**

Tensors in TensorFlow have three main characteristics:

1. **Shape:** Describes the structure of the tensor, like how many rows, columns, or layers it has. For example, a 2x3 matrix has a shape of (2, 3).
2. **Data Type:** Specifies what kind of numbers the tensor holds (e.g., integers like 1, 2, 3, or floating-point numbers like 1.5, 2.7).
3. **Values:** The actual numbers stored in the tensor.

For example:

- A tensor with the values [[1, 2], [3, 4]] is a 2x2 matrix (shape: (2, 2)), and if the numbers are decimals, the data type might be float32.

**Types of Tensors in TensorFlow**

TensorFlow uses different kinds of tensors depending on the task:

- **Constant Tensors:** Fixed values that don’t change (e.g., tf.constant([1, 2, 3])).
- **Variable Tensors:** Values that can change during training, like the weights in a neural network.
- **Placeholder Tensors:** Used in older versions of TensorFlow to hold data that will be provided later (less common now).
- **Sparse Tensors:** Tensors with mostly zero values, used to save memory for large datasets with lots of zeros.

**How Tensors Work in TensorFlow**

In TensorFlow, tensors flow through a computational graph (hence the name “TensorFlow”). A computational graph is like a recipe that says, “Take this data, do these calculations, and get this result.” Here’s a simple example of how tensors are used:

Example: Adding Two Numbers

Suppose you want to add 3 and 5 using TensorFlow:

- The numbers 3 and 5 are stored as tensors (0D tensors, or scalars).
- TensorFlow performs the addition operation on these tensors.
- The result is a new tensor with the value 8.

In code, it might look like this (don’t worry about the code details, it’s just for illustration):

```Python
import tensorflow as tf
a = tf.constant(3)  # Tensor with value 3
b = tf.constant(5)  # Tensor with value 5
c = a + b  # Tensor with value 8
```

# What is Deep Learning?

is a way to `teach computers to learn and make decisions like humans do`, using a method `inspired by how our brains work`. It’s a part of machine learning, where computers figure out patterns from data.

**Here’s a simple breakdown:**

- **Data:** You give the computer lots of examples, like pictures of cats and dogs.
- **Layers:** The computer uses a "neural network," which is like a stack of layers. Each layer looks at different features (e.g., edges, shapes, or colors in pictures).
- **Learning:** The computer adjusts itself by trial and error to get better at recognizing patterns, like telling cats from dogs.
- **Result:** After training, it can make predictions or decisions, like identifying a new picture as a cat.

# What is Machine Learning?

is like `teaching a computer to learn from examples so it can make decisions or predictions without being explicitly programmed`. Imagine teaching a child to recognize apples by showing them lots of apple pictures. The child learns what an apple looks like and can later pick out apples from other fruits. Machine learning works similarly: you give the computer data (examples), and `it figures out patterns to make smart guesses`.

**For example:**

- You show a computer thousands of emails labeled as "spam" or "not spam."
- It learns patterns (like certain words or phrases) to predict if a new email is spam.

### Differences Between Machine Learning and Deep Learning

| Description | Machine Learning | Deep Learning |
| ----------- | ---------------- | ------------- |
| **Simplicity** | Uses simpler methods to find patterns. It’s like teaching a computer a few specific rules to follow. | Uses many layers of neural networks to learn complex patterns automatically. It’s like teaching the computer to think more like a human. |
| **Data Needed** | Needs less data to work well. For example, a few hundred examples might be enough to predict house prices. | Needs lots of data, like thousands or millions of images, to recognize objects accurately. |
| **Human Input** | Often requires humans to pick important features (e.g., telling the computer to focus on email keywords like “free” or “win” for spam detection). | Figures out the important features on its own, so less human tweaking is needed. |
| **Computing Power** | Works fine on regular computers. | Needs powerful computers (like GPUs) because it does a lot more calculations. |
| **Examples** | Predicting house prices based on size and location, or detecting spam emails. | Recognizing faces in photos, powering self-driving cars, or understanding speech in voice assistants like Siri. |

**In Short**

- Machine Learning is like teaching a computer to solve problems with clear rules and patterns from data.
- Deep Learning is a more advanced version that learns complex patterns automatically using brain-like networks, but it needs more data and power.

# What is Neural Networks?

is a type of `machine learning algorithm inspired by how the human brain works`. It's a system of algorithms that tries to recognize patterns. In the simplest terms, it is like a digital brain that learns from data to make decisions or predictions.

It’s a system `made up of interconnected parts (called "neurons") that work together to process information, recognize patterns, and make predictions or decisions`. Imagine teaching a child to recognize cats in pictures: you show them lots of cat images, point out features like whiskers or pointy ears, and over time, they learn to spot cats on their own. Neural networks do something similar, but with math and data.

**Basic Structure:**

Imagine a neural network as a `series of connected layers`, much like a multi-layered cake. These layers are `made up of neurons (similar to the neurons in our brain)`, and they work together to process information.

- **Input Layer:** This is `where the neural network gets the information` (data). Think of it `as the "senses" of the brain that receive raw data`, like images, text, or numbers.
- **Hidden Layers:** These are intermediate `layers between the input and output`. They don’t directly interact with the outside world, but they are where the magic happens. In these layers, the `network analyzes the input and extracts patterns, relationships, or features`. The `more hidden layers there are, the deeper and more complex the network becomes` (this is what we call "deep learning").
- **Output Layer:** This is where the `final decision or prediction happens`. For example, if the neural network is trying to recognize a picture of a cat, the output might say "cat" or "dog" depending on what the network has learned.

**How does it learn?**

Neural networks `"learn"` through a process called training, and it requires data to do so. Here’s how it works:

1. **Forward Pass:** The input (e.g., an image) is passed through the network. It moves from one layer to the next, with each layer performing mathematical operations to transform the data. After passing through all the layers, the network produces an output.
2. **Error Calculation:** After getting the output, the network compares it to the correct answer (for example, if the correct answer was "cat," but the network said "dog"), and calculates an error. The error shows how far the network’s prediction was from the correct one.
3. **Backpropagation:** To fix the error, the network works backward, adjusting the weights (connections between neurons) to reduce the error. This process of making small adjustments is called backpropagation. It’s like a student reviewing their mistakes after a test and improving for next time.
4. **Repeat:** The network keeps repeating this cycle of forward pass, error calculation, and backpropagation until it gets good at making predictions. Over time, with enough data and adjustments, the network becomes better and better at recognizing patterns.

**Neurons and Weights:**

Each neuron in a layer is connected to the neurons in the next layer via weights. The weight determines the strength or importance of the connection. When data moves through the network, each weight is multiplied by the data, and the result is passed on to the next layer. The network adjusts these weights as it learns, gradually refining its decision-making process.

**Activation Function:**

Neurons don’t just pass information blindly; they make decisions based on an activation function. Think of this like a "gatekeeper" that decides whether a neuron should "fire" (send information forward) or not, based on the data it receives. Common activation functions include ReLU (Rectified Linear Unit) and Sigmoid.

**Why are Neural Networks powerful?**

Neural networks are powerful because:

- **They can learn complex patterns:** They can figure out very complicated relationships in data. For example, they can recognize faces in photos, understand spoken words, or predict stock prices based on past data.
- **They improve with more data:** The more examples (data) they are given, the better they get at understanding patterns.
- **They adapt:** The network continuously adjusts to improve accuracy, making them flexible for different types of tasks.

**Challenges of Neural Networks:**

- **They Need Lots of Data:** To learn well, they need thousands or millions of examples.
- **They’re Computationally Expensive:** Training a big neural network requires powerful computers and lots of time.
- **They Can Be Black Boxes:** It’s hard to understand why a neural network makes a certain decision, which can be a problem for things like medical diagnoses.
- **Overfitting:** Sometimes, the network learns the training data too well and fails to work on new data.

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.19.1'

**Scalar**

A scalar is just a `single number`. Think of it as something that has only magnitude and no direction or dimensions.

- Example: 5, -3, 2.7 are all scalars.

In [10]:
# create tensors with tf.constant()
# do not change during the execution of the code
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [11]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

1

**Vector**

A vector is a `list of numbers arranged in a specific order`. It’s like a row or column of numbers. A vector represents a direction and magnitude (think of it as an arrow in space).

- Example: [1,2,3] is a vector. It has 3 values and can be visualized as a point in 3D space.

In [17]:
# create a vector
vector = tf.constant([1,2,3,4,5,6,7,8,9])
vector

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [18]:
vector.ndim

1

**Matrix**

A matrix is a `2D array (a grid) of numbers, with rows and columns`. It’s like a table with numbers inside. Each number in the table is called an element.

Example:
[[1,2], [3,4], [5,6]]
This is a matrix with 3 rows and 2 columns.

In [31]:
# create a matrix
matrix = tf.constant([[1,2,3], [4,5,6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [20]:
matrix.ndim

2

**Tensor**

A tensor is a more general term for data that can `have multiple dimensions` (not just 1D like a vector, or 2D like a matrix). It’s a container for numbers arranged in a multi-dimensional grid.

- A **scalar** is a 0D tensor (just a single number).
- A **vector** is a 1D tensor (a list of numbers).
- A **matrix** is a 2D tensor (a table of numbers).
- A **3D tensor** would be like a cube of numbers (think of layers of matrices stacked on top of each other).

In [32]:
# create a tensor
tensor = tf.constant([[[1,2,3], [4,5,6]],
                     [[7,8,9], [10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [33]:
tensor.ndim

3

### Creating tensors with tf.Variable

is a special kind of tensor that is used for storing and `updating values` that are `meant to change during the training process of a machine learning model`. Unlike tf.constant (which is immutable), a tf.Variable `can be updated and modified during the execution of your model`, which makes it useful for things like `model parameters` (e.g., weights and biases) that need to be updated during training.

**Note:** Rarely in practive will you need to decide whether to use `tf.constant` and `tf.Variable` to create tensors, as Tensorflow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.

In [39]:
changeable_tensor = tf.Variable([10,20,30])
unchangeable_tensor = tf.constant([10,20,30])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 20, 30], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>)

In [43]:
# change the value of Variable of index 0
changeable_tensor[0].assign(100)
changeable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([100,  20,  30], dtype=int32)>

### Creating a random tensors

- **Random Uniform Tensor** (tf.random.uniform)

    This generates a tensor with random values sampled from a uniform distribution over a specified range.

- **Random Normal Tensor** (tf.random.normal)

    This generates a tensor with random values sampled from a normal (Gaussian) distribution with mean 0 and standard deviation 1 by default.

- **Random Bernoulli Tensor** (tf.random.stateless_binomial or tf.random.binomial)

    This generates a random tensor where each element is a random sample from a Bernoulli distribution.

- **Random Poisson Tensor** (tf.random.poisson)

    This generates a random tensor sampled from a Poisson distribution.

- **Random Integer Tensor** (tf.random.uniform with dtype=tf.int32)

    This generates a tensor with random integer values within a specified range.

- **Random Shuffle Tensor** (tf.random.shuffle)

    This doesn't generate a completely random tensor from scratch but shuffles an existing tensor randomly.

- **Random Gamma Tensor** (tf.random.gamma)

    This generates a random tensor from a Gamma distribution.

- **Random Zipf Tensor** (tf.random.zipf)

    Generates a tensor sampled from a Zipf distribution.

- **Random Exponential Tensor** (tf.random.exponential)

    Generates a tensor sampled from an exponential distribution.

- **Random Categorical Tensor** (tf.random.categorical)

    Samples random values from a categorical distribution. This is useful for situations like generating random classes.

In [45]:
normal_random = tf.random.Generator.from_seed(42) # set seed for reproducibility
normal_random = normal_random.normal(shape=(3,2))
normal_random

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>