# 00. Tensorflow Fundamentals

# What is Tensorflow?

is an open-source tool `created by Google to help build and run machine learning models`. Think of it like a `toolbox for teaching computers to learn from data`. It’s used for tasks like recognizing images, understanding speech, or predicting trends by processing lots of numbers and patterns.

**Other Resources**
- [Tensorflow Fundamentals](https://github.com/mrdbourke/tensorflow-deep-learning/blob/main/00_tensorflow_fundamentals.ipynb)
- [Rules of Machine Learning](https://developers.google.com/machine-learning/guides/rules-of-ml)

# What is a Tensor?

is a fundamental concept that represents data in a flexible, mathematical way.

A tensor is like a `container for numbers, organized in a specific shape`. Think of it as a way to store and manipulate data, whether it’s a single number, a list, a table, or even more complex structures. Tensors are the `building blocks that TensorFlow (an open-source AI library) uses to perform calculations, especially for tasks like training neural networks`.

You can picture tensors as:

- A single number (like 5).
- A list of numbers (like [1, 2, 3]).
- A table or grid of numbers (like a spreadsheet).
- Or even a 3D or higher-dimensional structure (like a stack of spreadsheets).

**Key Properties of a Tensor**

Tensors in TensorFlow have three main characteristics:

1. **Shape:** Describes the structure of the tensor, like how many rows, columns, or layers it has. For example, a 2x3 matrix has a shape of (2, 3).
2. **Data Type:** Specifies what kind of numbers the tensor holds (e.g., integers like 1, 2, 3, or floating-point numbers like 1.5, 2.7).
3. **Values:** The actual numbers stored in the tensor.

For example:

- A tensor with the values [[1, 2], [3, 4]] is a 2x2 matrix (shape: (2, 2)), and if the numbers are decimals, the data type might be float32.

**Types of Tensors in TensorFlow**

TensorFlow uses different kinds of tensors depending on the task:

- **Constant Tensors:** Fixed values that don’t change (e.g., tf.constant([1, 2, 3])).
- **Variable Tensors:** Values that can change during training, like the weights in a neural network.
- **Placeholder Tensors:** Used in older versions of TensorFlow to hold data that will be provided later (less common now).
- **Sparse Tensors:** Tensors with mostly zero values, used to save memory for large datasets with lots of zeros.

**How Tensors Work in TensorFlow**

In TensorFlow, tensors flow through a computational graph (hence the name “TensorFlow”). A computational graph is like a recipe that says, “Take this data, do these calculations, and get this result.” Here’s a simple example of how tensors are used:

Example: Adding Two Numbers

Suppose you want to add 3 and 5 using TensorFlow:

- The numbers 3 and 5 are stored as tensors (0D tensors, or scalars).
- TensorFlow performs the addition operation on these tensors.
- The result is a new tensor with the value 8.

In code, it might look like this (don’t worry about the code details, it’s just for illustration):

```Python
import tensorflow as tf
a = tf.constant(3)  # Tensor with value 3
b = tf.constant(5)  # Tensor with value 5
c = a + b  # Tensor with value 8
```

# What is Deep Learning?

is a way to `teach computers to learn and make decisions like humans do`, using a method `inspired by how our brains work`. It’s a part of machine learning, where computers figure out patterns from data.

**Here’s a simple breakdown:**

- **Data:** You give the computer lots of examples, like pictures of cats and dogs.
- **Layers:** The computer uses a "neural network," which is like a stack of layers. Each layer looks at different features (e.g., edges, shapes, or colors in pictures).
- **Learning:** The computer adjusts itself by trial and error to get better at recognizing patterns, like telling cats from dogs.
- **Result:** After training, it can make predictions or decisions, like identifying a new picture as a cat.

# What is Machine Learning?

is like `teaching a computer to learn from examples so it can make decisions or predictions without being explicitly programmed`. Imagine teaching a child to recognize apples by showing them lots of apple pictures. The child learns what an apple looks like and can later pick out apples from other fruits. Machine learning works similarly: you give the computer data (examples), and `it figures out patterns to make smart guesses`.

**For example:**

- You show a computer thousands of emails labeled as "spam" or "not spam."
- It learns patterns (like certain words or phrases) to predict if a new email is spam.

### Differences Between Machine Learning and Deep Learning

| Description | Machine Learning | Deep Learning |
| ----------- | ---------------- | ------------- |
| **Simplicity** | Uses simpler methods to find patterns. It’s like teaching a computer a few specific rules to follow. | Uses many layers of neural networks to learn complex patterns automatically. It’s like teaching the computer to think more like a human. |
| **Data Needed** | Needs less data to work well. For example, a few hundred examples might be enough to predict house prices. | Needs lots of data, like thousands or millions of images, to recognize objects accurately. |
| **Human Input** | Often requires humans to pick important features (e.g., telling the computer to focus on email keywords like “free” or “win” for spam detection). | Figures out the important features on its own, so less human tweaking is needed. |
| **Computing Power** | Works fine on regular computers. | Needs powerful computers (like GPUs) because it does a lot more calculations. |
| **Examples** | Predicting house prices based on size and location, or detecting spam emails. | Recognizing faces in photos, powering self-driving cars, or understanding speech in voice assistants like Siri. |

**In Short**

- Machine Learning is like teaching a computer to solve problems with clear rules and patterns from data.
- Deep Learning is a more advanced version that learns complex patterns automatically using brain-like networks, but it needs more data and power.

# What is Neural Networks?

is a type of `machine learning algorithm inspired by how the human brain works`. It's a system of algorithms that tries to recognize patterns. In the simplest terms, it is like a digital brain that learns from data to make decisions or predictions.

It’s a system `made up of interconnected parts (called "neurons") that work together to process information, recognize patterns, and make predictions or decisions`. Imagine teaching a child to recognize cats in pictures: you show them lots of cat images, point out features like whiskers or pointy ears, and over time, they learn to spot cats on their own. Neural networks do something similar, but with math and data.

**Basic Structure:**

Imagine a neural network as a `series of connected layers`, much like a multi-layered cake. These layers are `made up of neurons (similar to the neurons in our brain)`, and they work together to process information.

- **Input Layer:** This is `where the neural network gets the information` (data). Think of it `as the "senses" of the brain that receive raw data`, like images, text, or numbers.
- **Hidden Layers:** These are intermediate `layers between the input and output`. They don’t directly interact with the outside world, but they are where the magic happens. In these layers, the `network analyzes the input and extracts patterns, relationships, or features`. The `more hidden layers there are, the deeper and more complex the network becomes` (this is what we call "deep learning").
- **Output Layer:** This is where the `final decision or prediction happens`. For example, if the neural network is trying to recognize a picture of a cat, the output might say "cat" or "dog" depending on what the network has learned.

**How does it learn?**

Neural networks `"learn"` through a process called training, and it requires data to do so. Here’s how it works:

1. **Forward Pass:** The input (e.g., an image) is passed through the network. It moves from one layer to the next, with each layer performing mathematical operations to transform the data. After passing through all the layers, the network produces an output.
2. **Error Calculation:** After getting the output, the network compares it to the correct answer (for example, if the correct answer was "cat," but the network said "dog"), and calculates an error. The error shows how far the network’s prediction was from the correct one.
3. **Backpropagation:** To fix the error, the network works backward, adjusting the weights (connections between neurons) to reduce the error. This process of making small adjustments is called backpropagation. It’s like a student reviewing their mistakes after a test and improving for next time.
4. **Repeat:** The network keeps repeating this cycle of forward pass, error calculation, and backpropagation until it gets good at making predictions. Over time, with enough data and adjustments, the network becomes better and better at recognizing patterns.

**Neurons and Weights:**

Each neuron in a layer is connected to the neurons in the next layer via weights. The weight determines the strength or importance of the connection. When data moves through the network, each weight is multiplied by the data, and the result is passed on to the next layer. The network adjusts these weights as it learns, gradually refining its decision-making process.

**Activation Function:**

Neurons don’t just pass information blindly; they make decisions based on an activation function. Think of this like a "gatekeeper" that decides whether a neuron should "fire" (send information forward) or not, based on the data it receives. Common activation functions include ReLU (Rectified Linear Unit) and Sigmoid.

**Why are Neural Networks powerful?**

Neural networks are powerful because:

- **They can learn complex patterns:** They can figure out very complicated relationships in data. For example, they can recognize faces in photos, understand spoken words, or predict stock prices based on past data.
- **They improve with more data:** The more examples (data) they are given, the better they get at understanding patterns.
- **They adapt:** The network continuously adjusts to improve accuracy, making them flexible for different types of tasks.

**Challenges of Neural Networks:**

- **They Need Lots of Data:** To learn well, they need thousands or millions of examples.
- **They’re Computationally Expensive:** Training a big neural network requires powerful computers and lots of time.
- **They Can Be Black Boxes:** It’s hard to understand why a neural network makes a certain decision, which can be a problem for things like medical diagnoses.
- **Overfitting:** Sometimes, the network learns the training data too well and fails to work on new data.

In [94]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.19.1'

**Scalar**

A scalar is just a `single number`. Think of it as something that has only magnitude and no direction or dimensions.

- Example: 5, -3, 2.7 are all scalars.

In [95]:
# create tensors with tf.constant()
# do not change during the execution of the code
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

**Vector**

A vector is a `list of numbers arranged in a specific order`. It’s like a row or column of numbers. A vector represents a direction and magnitude (think of it as an arrow in space).

- Example: [1,2,3] is a vector. It has 3 values and can be visualized as a point in 3D space.

In [5]:
# create a vector
vector = tf.constant([1,2,3,4,5,6,7,8,9])
vector

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [6]:
vector.ndim

1

**Matrix**

A matrix is a `2D array (a grid) of numbers, with rows and columns`. It’s like a table with numbers inside. Each number in the table is called an element.

Example:
[[1,2], [3,4], [5,6]]
This is a matrix with 3 rows and 2 columns.

In [7]:
# create a matrix
matrix = tf.constant([[1,2,3], [4,5,6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [8]:
matrix.ndim

2

**Tensor**

A tensor is a more general term for data that can `have multiple dimensions` (not just 1D like a vector, or 2D like a matrix). It’s a container for numbers arranged in a multi-dimensional grid.

- A **scalar** is a 0D tensor (just a single number).
- A **vector** is a 1D tensor (a list of numbers).
- A **matrix** is a 2D tensor (a table of numbers).
- A **3D tensor** would be like a cube of numbers (think of layers of matrices stacked on top of each other).

In [9]:
# create a tensor
tensor = tf.constant([[[1,2,3], [4,5,6]],
                     [[7,8,9], [10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [10]:
tensor.ndim

3

### Creating tensors with tf.Variable

is a special kind of tensor that is used for storing and `updating values` that are `meant to change during the training process of a machine learning model`. Unlike tf.constant (which is immutable), a tf.Variable `can be updated and modified during the execution of your model`, which makes it useful for things like `model parameters` (e.g., weights and biases) that need to be updated during training.

**Note:** Rarely in practive will you need to decide whether to use `tf.constant` and `tf.Variable` to create tensors, as Tensorflow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.

In [11]:
changeable_tensor = tf.Variable([10,20,30])
unchangeable_tensor = tf.constant([10,20,30])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 20, 30], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>)

In [12]:
# change the value of Variable of index 0
changeable_tensor[0].assign(100)
changeable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([100,  20,  30], dtype=int32)>

### Creating a random tensors

- **Random Uniform Tensor** (`tf.random.uniform`): This generates a tensor with random values sampled from a uniform distribution over a specified range.

- **Random Normal Tensor** (`tf.random.normal`): This generates a tensor with random values sampled from a normal (Gaussian) distribution with mean 0 and standard deviation 1 by default.

- **Random Bernoulli Tensor** (`tf.random.stateless_binomial` or `tf.random.binomial`): This generates a random tensor where each element is a random sample from a Bernoulli distribution.

- **Random Poisson Tensor** (`tf.random.poisson`): This generates a random tensor sampled from a Poisson distribution.

- **Random Integer Tensor** (`tf.random.uniform` with dtype=tf.int32): This generates a tensor with random integer values within a specified range.

- **Random Shuffle Tensor** (`tf.random.shuffle`): This doesn't generate a completely random tensor from scratch but shuffles an existing tensor randomly.

- **Random Gamma Tensor** (`tf.random.gamma`): This generates a random tensor from a Gamma distribution.

- **Random Zipf Tensor** (`tf.random.zipf`): Generates a tensor sampled from a Zipf distribution.

- **Random Exponential Tensor** (`tf.random.exponential`): Generates a tensor sampled from an exponential distribution.

- **Random Categorical Tensor** (`tf.random.categorical`): Samples random values from a categorical distribution. This is useful for situations like generating random classes.

In [13]:
normal_random = tf.random.Generator.from_seed(42) # set seed for reproducibility
normal_random = normal_random.normal(shape=(3,2))
normal_random

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

### Shuffle the order of elements in a tensor

In [14]:
# create not shuffled tensor
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_shuffled.ndim

2

In [15]:
# shuffle our not_shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

### Other ways to make tensors

- `tf.zeros()` Creates a tensor filled with zeros of the specified shape.

In [16]:
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

- `tf.eye()` Creates a 2-D tensor with ones on the diagonal and zeros elsewhere (identity matrix).

In [17]:
tf.eye(4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

- `tf.linspace()` Creates a tensor of evenly spaced values over a specified range.

In [18]:
tf.linspace(0.0, 10, 5)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=float32)>

### Turn Numpy arrays into tensors

The main difference between Numpy arrays and TensorFlow is that tensors can be run on a GPU

In [19]:
np_array = np.arange(0, 100, dtype=np.float32)
np_array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.], dtype=float32)

In [20]:
t_array = tf.constant(np_array, shape=(5, 5, 4))
t_array

<tf.Tensor: shape=(5, 5, 4), dtype=float32, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]],

       [[20., 21., 22., 23.],
        [24., 25., 26., 27.],
        [28., 29., 30., 31.],
        [32., 33., 34., 35.],
        [36., 37., 38., 39.]],

       [[40., 41., 42., 43.],
        [44., 45., 46., 47.],
        [48., 49., 50., 51.],
        [52., 53., 54., 55.],
        [56., 57., 58., 59.]],

       [[60., 61., 62., 63.],
        [64., 65., 66., 67.],
        [68., 69., 70., 71.],
        [72., 73., 74., 75.],
        [76., 77., 78., 79.]],

       [[80., 81., 82., 83.],
        [84., 85., 86., 87.],
        [88., 89., 90., 91.],
        [92., 93., 94., 95.],
        [96., 97., 98., 99.]]], dtype=float32)>

### Getting information from tensors

- **Shape** The length (number of elements) of each of the dimensions of a tensor, `tensor.shape`
- **Rank** The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n `tensor.ndim`
- **Axis or dimension** A particular dimentsion of a tensor `tensor[0]`, `tensor[:, 1]`
- **Size** The total number of items in the tensor `tf.size(tensor)`

In [21]:
t_array.shape

TensorShape([5, 5, 4])

In [22]:
t_array.ndim

3

In [23]:
t_array[0], t_array[-1]

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[80., 81., 82., 83.],
        [84., 85., 86., 87.],
        [88., 89., 90., 91.],
        [92., 93., 94., 95.],
        [96., 97., 98., 99.]], dtype=float32)>)

In [24]:
tf.size(t_array), tf.size(t_array).numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=100>, 100)

### Indexing tensors

Tensors can be indexed just like Python lists

In [25]:
some_list = [1,2,3,4,5]
some_list[:2]

[1, 2]

In [26]:
t_array[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[ 0.,  1.],
        [ 4.,  5.]],

       [[20., 21.],
        [24., 25.]]], dtype=float32)>

In [27]:
# get the firs element from each dimension from each index except for the final one
t_array[:1,:1,:]

<tf.Tensor: shape=(1, 1, 4), dtype=float32, numpy=array([[[0., 1., 2., 3.]]], dtype=float32)>

In [28]:
some_list[-1], t_array[:, :, -1]

(5,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[ 3.,  7., 11., 15., 19.],
        [23., 27., 31., 35., 39.],
        [43., 47., 51., 55., 59.],
        [63., 67., 71., 75., 79.],
        [83., 87., 91., 95., 99.]], dtype=float32)>)

In [29]:
rank_tensor = tf.constant([[1,2], [3,4]])
rank_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [30]:
# add in extra dimension to our tensor
rank_tensor_extra = rank_tensor[..., tf.newaxis]
rank_tensor_extra

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [31]:
# alternative to tf.newaxis
tf.expand_dims(rank_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [32]:
# expand 0 axis
tf.expand_dims(rank_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Arithmetic Operations**

Element-wise or matrix math on tensors.

+, -, *, /

- `tf.add(x, y)` Adds tensors element-wise (broadcasts if shapes compatible).
- `tf.subtract(x, y)` Subtracts tensors element-wise.
- `tf.multiply(x, y)` Multiplies tensors element-wise.
- `tf.divide(x, y)` Divides tensors element-wise.
- `tf.square(x)` Squares each element.
- `tf.matmul(x, y)` Performs matrix multiplication.

**Reshaping Operations**

Change tensor shape without altering data.

- `tf.reshape(tensor, shape)` Reshapes tensor (use -1 to infer one dimension).
- `tf.transpose(tensor, perm=None)` Transposes axes (e.g., swap rows/columns).

**Type and Broadcasting Operations**

Handle data types and shape expansion.

- `tf.cast(tensor, dtype)` Changes tensor's data type (may lose precision).
- `tf.broadcast_to(tensor, shape)` Expands tensor to new shape via broadcasting.

**Reduction Operations**

Aggregate values across axes (e.g., sum over dimensions).

- `tf.reduce_sum(tensor, axis=None)` Sums elements along specified axis (or all for scalar).
- `tf.reduce_mean(tensor, axis=None)` Computes mean along axis.
- `tf.reduce_max(tensor, axis=None)` Finds maximum along axis.
- `tf.math.argmax(tensor, axis=None)` Returns indices of max values along axis.

In [33]:
t_array + 10

<tf.Tensor: shape=(5, 5, 4), dtype=float32, numpy=
array([[[ 10.,  11.,  12.,  13.],
        [ 14.,  15.,  16.,  17.],
        [ 18.,  19.,  20.,  21.],
        [ 22.,  23.,  24.,  25.],
        [ 26.,  27.,  28.,  29.]],

       [[ 30.,  31.,  32.,  33.],
        [ 34.,  35.,  36.,  37.],
        [ 38.,  39.,  40.,  41.],
        [ 42.,  43.,  44.,  45.],
        [ 46.,  47.,  48.,  49.]],

       [[ 50.,  51.,  52.,  53.],
        [ 54.,  55.,  56.,  57.],
        [ 58.,  59.,  60.,  61.],
        [ 62.,  63.,  64.,  65.],
        [ 66.,  67.,  68.,  69.]],

       [[ 70.,  71.,  72.,  73.],
        [ 74.,  75.,  76.,  77.],
        [ 78.,  79.,  80.,  81.],
        [ 82.,  83.,  84.,  85.],
        [ 86.,  87.,  88.,  89.]],

       [[ 90.,  91.,  92.,  93.],
        [ 94.,  95.,  96.,  97.],
        [ 98.,  99., 100., 101.],
        [102., 103., 104., 105.],
        [106., 107., 108., 109.]]], dtype=float32)>

In [34]:
t_array * 10

<tf.Tensor: shape=(5, 5, 4), dtype=float32, numpy=
array([[[  0.,  10.,  20.,  30.],
        [ 40.,  50.,  60.,  70.],
        [ 80.,  90., 100., 110.],
        [120., 130., 140., 150.],
        [160., 170., 180., 190.]],

       [[200., 210., 220., 230.],
        [240., 250., 260., 270.],
        [280., 290., 300., 310.],
        [320., 330., 340., 350.],
        [360., 370., 380., 390.]],

       [[400., 410., 420., 430.],
        [440., 450., 460., 470.],
        [480., 490., 500., 510.],
        [520., 530., 540., 550.],
        [560., 570., 580., 590.]],

       [[600., 610., 620., 630.],
        [640., 650., 660., 670.],
        [680., 690., 700., 710.],
        [720., 730., 740., 750.],
        [760., 770., 780., 790.]],

       [[800., 810., 820., 830.],
        [840., 850., 860., 870.],
        [880., 890., 900., 910.],
        [920., 930., 940., 950.],
        [960., 970., 980., 990.]]], dtype=float32)>

In [35]:
t_array - .5

<tf.Tensor: shape=(5, 5, 4), dtype=float32, numpy=
array([[[-0.5,  0.5,  1.5,  2.5],
        [ 3.5,  4.5,  5.5,  6.5],
        [ 7.5,  8.5,  9.5, 10.5],
        [11.5, 12.5, 13.5, 14.5],
        [15.5, 16.5, 17.5, 18.5]],

       [[19.5, 20.5, 21.5, 22.5],
        [23.5, 24.5, 25.5, 26.5],
        [27.5, 28.5, 29.5, 30.5],
        [31.5, 32.5, 33.5, 34.5],
        [35.5, 36.5, 37.5, 38.5]],

       [[39.5, 40.5, 41.5, 42.5],
        [43.5, 44.5, 45.5, 46.5],
        [47.5, 48.5, 49.5, 50.5],
        [51.5, 52.5, 53.5, 54.5],
        [55.5, 56.5, 57.5, 58.5]],

       [[59.5, 60.5, 61.5, 62.5],
        [63.5, 64.5, 65.5, 66.5],
        [67.5, 68.5, 69.5, 70.5],
        [71.5, 72.5, 73.5, 74.5],
        [75.5, 76.5, 77.5, 78.5]],

       [[79.5, 80.5, 81.5, 82.5],
        [83.5, 84.5, 85.5, 86.5],
        [87.5, 88.5, 89.5, 90.5],
        [91.5, 92.5, 93.5, 94.5],
        [95.5, 96.5, 97.5, 98.5]]], dtype=float32)>

In [36]:
t_array / 5

<tf.Tensor: shape=(5, 5, 4), dtype=float32, numpy=
array([[[ 0. ,  0.2,  0.4,  0.6],
        [ 0.8,  1. ,  1.2,  1.4],
        [ 1.6,  1.8,  2. ,  2.2],
        [ 2.4,  2.6,  2.8,  3. ],
        [ 3.2,  3.4,  3.6,  3.8]],

       [[ 4. ,  4.2,  4.4,  4.6],
        [ 4.8,  5. ,  5.2,  5.4],
        [ 5.6,  5.8,  6. ,  6.2],
        [ 6.4,  6.6,  6.8,  7. ],
        [ 7.2,  7.4,  7.6,  7.8]],

       [[ 8. ,  8.2,  8.4,  8.6],
        [ 8.8,  9. ,  9.2,  9.4],
        [ 9.6,  9.8, 10. , 10.2],
        [10.4, 10.6, 10.8, 11. ],
        [11.2, 11.4, 11.6, 11.8]],

       [[12. , 12.2, 12.4, 12.6],
        [12.8, 13. , 13.2, 13.4],
        [13.6, 13.8, 14. , 14.2],
        [14.4, 14.6, 14.8, 15. ],
        [15.2, 15.4, 15.6, 15.8]],

       [[16. , 16.2, 16.4, 16.6],
        [16.8, 17. , 17.2, 17.4],
        [17.6, 17.8, 18. , 18.2],
        [18.4, 18.6, 18.8, 19. ],
        [19.2, 19.4, 19.6, 19.8]]], dtype=float32)>

In [37]:
# matrix multiplication
a = tf.constant([[1, 2], [3, 4]]); 
b = tf.constant([[5], [6]]);

a, b, tf.matmul(a, b)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[5],
        [6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[17],
        [39]], dtype=int32)>)

In [38]:
# reshape
t = tf.constant([[1, 2], [3, 4]]); 
tf.reshape(t, [-1]) # [1 2 3 4]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [39]:
# transpose
tf.transpose(t, perm=None) # [[1, 3], [2, 4]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

### Changing tensor data type

- `tf.cast(tensor, dtype)` Converts a tensor to a new dtype.
- `tf.dtypes.cast(tensor, dtype)` This is another way to cast a tensor to a new dtype, similar to tf.cast(). It is just an alias to tf.cast()
- `tf.float32(), tf.float64(), tf.int32(), tf.int64() (Explicit Type Constructors)` You can use explicit type constructors to create a new tensor of a specific dtype.
- `tf.convert_to_tensor(value, dtype=None)` Converts a Python object (like a NumPy array or a list) to a TensorFlow tensor with the desired dtype.
- `tf.keras.backend.cast(tensor, dtype)` If you're using the Keras API and you want to cast a tensor, you can use tf.keras.backend.cast().
- `tf.math.cast(tensor, dtype)` (Less Common) A TensorFlow operation that allows casting to different dtypes. This is very similar to tf.cast() but used explicitly in the math context.
- `tf.Tensor.astype()` (Numpy-style conversion) While TensorFlow doesn’t have a .astype() method directly like NumPy, tf.cast() and other functions serve as the equivalent.

In [40]:
# cast to float16
tf.cast(t, dtype=tf.float16)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [41]:
# cast float to int
t_float = tf.constant([[1.2,35.2,52.2], [100.2,12.52,66.23]])
tf.cast(t_float, dtype=tf.int16)

<tf.Tensor: shape=(2, 3), dtype=int16, numpy=
array([[  1,  35,  52],
       [100,  12,  66]], dtype=int16)>

### TensorFlow Tensor Aggregations

provides a variety of reduction functions in the tf.math module to aggregate or reduce tensors along specified dimensions (e.g., summing or averaging elements).

| Function | Description |
|--------- | -------------|
| **tf.math.reduce_sum** | Computes the sum of elements across specified dimensions of a tensor. |
| **tf.math.reduce_mean** | Computes the arithmetic mean (average) of elements across dimensions. |
| **tf.math.reduce_max** | Computes the maximum value across dimensions. |
| **tf.math.reduce_min** | Computes the minimum value across dimensions. |
| **tf.math.reduce_prod** | Computes the product of elements across dimensions. |
| **tf.math.reduce_std** | Computes the standard deviation of elements across dimensions. |
| **tf.math.reduce_variance** | Computes the variance of elements across dimensions. |
| **tf.math.reduce_euclidean_norm** | Computes the Euclidean (L2) norm across dimensions. |
| **tf.math.reduce_logsumexp** | Computes the log of the sum of exponentials, useful for numerical stability in probabilities. |
| **tf.math.count_nonzero** | Counts the number of non-zero elements across dimensions. |

**Cumulative (Positional Prefix) Aggregations**

These compute running totals or similar along specified axes, useful for tasks like sequence modeling or financial calculations.

| Function | Description |
| -------- | ----------- |
| **tf.math.cumsum** | Computes the cumulative sum of elements along the specified axis. |
| **tf.math.cumprod** | Computes the cumulative product of elements along the specified axis. |
| **tf.math.cumulative_logsumexp** | Computes the cumulative log-sum-exp of elements along the specified axis, aiding numerical stability in probabilistic sequences. |

**Argument (Position-Returning) Aggregations**

These return the indices (positions) of the aggregated values, often used in sorting, top-k selection, or optimization.

| Function | Description |
| -------- | ----------- |
| **tf.math.argmax** | Returns the index of the maximum value along the specified axis. |
| **tf.math.argmin** | Returns the index of the minimum value along the specified axis. |
| **tf.math.top_k** | Computes the top-k values and their corresponding indices along the last axis (returns both values and positions). |

In [63]:
E = tf.constant(np.random.randint(0, 100, size=50), dtype=tf.float64)
E

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([67., 37., 42., 27., 38., 90., 37.,  8., 92., 18., 38., 85., 35.,
       74., 97., 98., 24., 74., 16., 78., 95., 46., 98., 69., 26., 70.,
       90., 51., 39., 87., 63., 80., 91.,  1., 41.,  3., 40., 10.,  4.,
       41., 43., 21.,  7., 98., 81., 90., 19., 11., 65., 63.])>

In [55]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [56]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=float64, numpy=0.0>

In [57]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=float64, numpy=99.0>

In [58]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=float64, numpy=2545.0>

In [59]:
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float64, numpy=781.6499999999999>

In [64]:
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float64, numpy=30.88803004401543>

In [66]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [67]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [68]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [69]:
tf.math.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

### Squaring, log & square root

In [90]:
H = tf.range(1, 10, dtype=tf.float64)
H

<tf.Tensor: shape=(9,), dtype=float64, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.])>

In [93]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float64, numpy=
array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])>

In [91]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=float64, numpy=array([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.])>

In [92]:
tf.math.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float64, numpy=
array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])>

### Squeezing a tensor (Removing all single dimensions)

In [74]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G, G.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
            0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
            0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
            0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
            0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
            0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

In [75]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding of tensors

refers to the output of the tf.one_hot function, which `transforms a tensor of categorical indices into a sparse representation where each index is encoded as a vector with a single "hot" (active) value` at the corresponding position and zeros (or off-values) elsewhere. This is a standard technique in machine learning for handling categorical data, such as class labels in classification tasks.

**Purpose**

- Converts integer indices (e.g., class labels like [0, 1, 2]) into dense one-hot vectors, making them suitable for operations like softmax or embedding layers.
- Helps avoid ordinal assumptions in models by treating categories as independent.

**How It Works**

- **Input:** A tensor of indices (e.g., shape [batch_size, features]) and a scalar depth (number of categories).
- **Output:** A new tensor with shape expanded by 1 (e.g., [batch_size, features, depth]), where the axis (default: last) holds the one-hot dimension.
- The value at position indices[j] is set to on_value (default: 1), and others to off_value (default: 0).

In [80]:
lst = [0,1,2,3] # Tensor of indices to encode, could be red, green, blue, purple
depth = 4 # Number of categories (scalar)

tf.one_hot(lst, depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [82]:
tf.one_hot(lst, depth=4, on_value="Yes", off_value="No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

### Finding access to GPU

In [96]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]